
    <div id="body">
        <header>A simple guy in <strong>St. Thomas, USVI</strong> with a "thing" for <strong>PHP</strong>.</header>
        <div id="bar">
            <h1><a href="#" id="link">Philip Gabbert Jr.</a></h1>
            <ul id="online-portals">
                <li><a href="http://www.facebook.com/guice" title="For my Friends and Family"><img src="/images/facebook.png" alt="Facebook" /></a></li>
                <li><a href="http://twitter.com/#!/guice" title="Open to all"><img src="/images/twitter.png" alt="Twitter" /></a></li>
                <li><a href="http://www.linkedin.com/in/guice" title="Professional Contacts"><img src="/images/linkedin.png" alt="LinkedIn" /></a></li>
                <li><a href="http://guice.smugmug.com/" title="Photo Album" ><img src="/images/smugmug.png" alt="SmugMug" /></a></li>
            </ul>
            <div id="extra">
                <img src="/images/icon.jpg" id="icon" />
                <p id="bio">
                    I'm a simple single <?= intval((time() - strtotime('Sept. 30 1976')) / (31556926)) ?> year old guy living life the best
                    one can in the Virigin Islands. I moved down here in April, '11 for a new Sr. PHP position with <a href="http://www.glacialenergy.com/">Glacial Energy</a>,
                    and I have yet to regret it.
                    <br />
                    <br />
                    I'm currently not on the market for a new position, but if you feel you can beat Glacial, and the Virigin Islands:
                    I'm a <a href="http://zce.gpcentre.net/" alt="PHP5 ZCE">Zend Certified Engineer</a>; you can find my <a href="http://www.gpcentre.net/documents/resume/">resume online</a>, as well as some <a href="">sample code</a>.
                </p>
                <br class="clear" />
            </div>
        </div>
        <footer>
          <span class="email">g<span class="sans-bot">anti-bot</span>p@gp<span class="sans-bot">anti-bot</span>centre.ne<span class="sans-bot">anti-bot</span>t</span>
          <span class="validators"><a href="http://jigsaw.w3.org/css-validator/check/referer">CSS3</a> |
          <a href="http://validator.w3.org/check/referer">HTML 5</a></span>

        </footer>
    </div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#link').click(function() {
            $('div#extra').slideToggle('medium');
            return false;
        });
    });
</script>