
    <div id="body">
        <header>A simple guy in <strong>St. Thomas, USVI</strong> with a "thing" for <strong>PHP</strong>.</header>
        <div id="bar">
            <h1><a href="" id="link">Philip Gabbert Jr.</a></h1>
            <ul id="online-portals">
                <li><a href="https://plus.google.com/105981717032173537224/" title="Google +"" ><img src="/images/google-plus.png" alt="Google+" /></a></li>
                <li><a href="http://www.facebook.com/guice" title="For my Friends and Family"><img src="/images/facebook.png" alt="Facebook" /></a></li>
                <li><a href="http://twitter.com/#!/guice" title="Open to all"><img src="/images/twitter.png" alt="Twitter" /></a></li>
                <li><a href="http://www.linkedin.com/in/guice" title="Lets keep it professional"><img src="/images/linkedin.png" alt="LinkedIn" /></a></li>
            </ul>
            <div id="extra">
                <img src="/images/icon.jpg" id="icon" />
                <p id="bio">
                    I'm a simple <?= intval((time() - strtotime('Sept. 30 1976')) / (31556926)) ?> year old single guy living life the best
                    one can in the Virigin Islands. I moved down here in April, '11 for a new Sr. PHP position with <a href="http://www.glacialenergy.com/">Glacial Energy</a>,
                    and I have yet to regret it.
                    <br />
                    <br />
                    I'm currently not on the market, but if you feel you can beat Glacial, and the Virigin Islands, you're welcomed to try.
                    I'm a <a href="http://www.zend.com/zce.php?c=ZEND901133&r=0502143">Zend Certified Engineer</a>; you can find my <a href="/documents/resume/">resume online</a>, as well as some <a href="/downloads/alarm.zip">sample code</a>.
                </p>
                <br class="clear" />
            </div>
        </div>
        <footer>
          <span class="email">g<span class="sans-bot">anti-bot</span>p@gp<span class="sans-bot">anti-bot</span>centre.ne<span class="sans-bot">anti-bot</span>t</span>
          <span class="validators"><a href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3" title="Yes, this site is valid CSS3. Blame W3C for the ONE error: http://bit.ly/hGRTvq">CSS3</a> |
          <a href="http://validator.w3.org/check/referer">HTML 5</a></span>
        </footer>
        <div class="awesome">
            <h2>Be <span></span></h2>
        </div>
    </div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#link').click(function(e) {
            $('div#extra').slideToggle('medium');
            e.preventDefault();
        });
    });
</script>
