<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>GPCentre.net :: Philip Gabbert Jr.</title>
    <link href="/css/reset.css" rel="stylesheet" type="text/css" />
    <link href="/css/back-stab.css" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
</head>
<body>

<? echo $this->layout()->content; ?>

</body>
</html>
